#!/usr/bin/env python3
"""Regenerate requirements.txt and requirements-dev.txt (exact versions) from the .in files.

    python scripts/python/lock.py      # dev machine, repo root; needs Docker

pip resolves packages for the platform it runs on, and Cortex runs on Linux (the container
and CI), so this installs each .in file into a clean copy of the same Linux image the
Dockerfile uses and records the result with `pip freeze`. Commit both .txt files.

  requirements.in      -> requirements.txt      what the Docker image installs
  requirements-dev.in  -> requirements-dev.txt  what CI and local development install
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
# Keep in step with the FROM line in the Dockerfile.
IMAGE = "python:3.14-slim@sha256:51dafde81dbdb6ebde285137a295cf18a47ca95234fe388a343719cb97305b3d"
PAIRS = [("requirements.in", "requirements.txt"), ("requirements-dev.in", "requirements-dev.txt")]
HEADER = "# Generated by scripts/python/lock.py from {source} (Linux, Python 3.14). Don't edit by hand.\n"


def freeze(source: str) -> str:
    """Install one .in file into a clean container and return `pip freeze` of the result.

    Args:
        source: the .in file, relative to the repo root.

    Returns:
        The frozen requirements, one `name==version` per line.
    """
    script = f"pip install --quiet --root-user-action=ignore --disable-pip-version-check -r {source} && pip freeze"
    command = ["docker", "run", "--rm", "-v", f"{ROOT}:/src:ro", "-w", "/src", IMAGE, "sh", "-c", script]
    result = subprocess.run(command, env={**os.environ, "MSYS_NO_PATHCONV": "1"}, check=True, capture_output=True, text=True)
    return result.stdout


def main() -> int:
    """Regenerate every .txt file from its .in file.

    Returns:
        0 when all files were written; 1 when an install failed.
    """
    for source, target in PAIRS:
        try:
            frozen = freeze(source)
        except subprocess.CalledProcessError as error:
            print(f"couldn't resolve {source}:\n{error.stderr}", file=sys.stderr)
            return 1
        (ROOT / target).write_text(HEADER.format(source=source) + frozen, encoding="utf-8", newline="\n")
        print(f"wrote {target} ({len(frozen.splitlines())} packages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
